name: CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['12.x', '14.x']
    steps:
    - name: Set GOPATH
      run: |
          echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
          echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
          echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin/windows_386"
      shell: bash
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.1
    - name: Set GO Version
      run: |
          echo "##[set-env name=GOPHERJS_GOROOT;]$(go1.17.1 env GOROOT)"
      shell: bash
    - name: Install gopherjs
      run: go get -u github.com/gopherjs/gopherjs
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Run CI
      run: npm test
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: './target/coverage/report/lcov.info'
